### ISSUE TITLE
Just JS?

### ISSUE THREAD

**Issue by EpicMStudios** [idea-lab/Labs#1]
Are we only doing JS for the labs?

**Comment by skyli42** [comment]
I'm doing html/css/js for calculator right now since I'm not sure what else we have

**Comment by skyli42** [comment]
We can switch

**Comment by ctrotz** [comment]
Guys we talked about this. We're doing python. I'm at debate camp rn so I
don't really have time to work, but get started on python

**Comment by EpicMStudios** [comment]
Sorry bud. I'm starting with JS because python is overkill for half the labs.
